AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SNSTopicParameter:
    Type: String
    Default: arn:aws:sns:eu-west-1:137522687226:TestTopic
    Description: SNS topic for alerts

Description: EC2
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06ed60ed1369448bd
      SecurityGroups:
        - default
      InstanceType: t2.micro
      KeyName: Callum-Blog
      BlockDeviceMappings:
        - DeviceName: /dev/sdh
          Ebs:
            VolumeType: gp3
            DeleteOnTermination: false
            VolumeSize: 5

  MyBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: "80% budget"
        BudgetLimit:
          Amount: 10
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: EQUAL_TO
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: callumness1@live.co.uk

  EBSVolumeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: EBS Volume Storage 90%
      AlarmDescription: Alarm for EBS volume storage threshold
      Namespace: AWS/EBS
      MetricName: VolumeUsedSize
      Dimensions:
        - Name: VolumeId
          Value: vol-0d712550a7758f2ce
      ComparisonOperator: GreaterThanThreshold
      Threshold: 90
      Period: 300
      EvaluationPeriods: 1
      Statistic: SampleCount
      AlarmActions:
        - !Ref SNSTopicParameter
      OKActions:
        - !Ref SNSTopicParameter

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Rider"
          AttributeType: "S"
        - AttributeName: "Brand"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Rider"
          KeyType: "HASH"
        - AttributeName: "Brand"
          KeyType: "RANGE"
      BillingMode: PROVISIONED
      TableName: "Riders_Qualifying_and_Race_Times"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  BudgetId:
    Value: !Ref MyBudget
